CREATE TABLE IF NOT EXISTS SOURCES (ID SERIAL PRIMARY KEY, NAME TEXT UNIQUE);

CREATE TABLE IF NOT EXISTS KEYWORD_RANKINGS (
	ID SERIAL PRIMARY KEY,
	KEYWORD TEXT,
	COUNT INT,
	RANK INT,
	COLLECTED_AT DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS ARTICLES (
	ID SERIAL PRIMARY KEY,
	TITLE TEXT,
	AUTHOR TEXT,
	DESCRIPTION TEXT,
	URL TEXT UNIQUE,
	PUBLISHED_AT TIMESTAMP,
	SOURCE_ID INT REFERENCES SOURCES (ID)
);