SELECT
	S.NAME AS PUBLICATION,
	A.TITLE AS ARTICLE_TITLE,
	A.PUBLISHED_AT
FROM
	ARTICLES A
	JOIN SOURCES S ON A.SOURCE_ID = S.ID
WHERE
	A.TITLE ILIKE '%weride%'
	AND A.PUBLISHED_AT = (
		SELECT
			MIN(PUBLISHED_AT)
		FROM
			ARTICLES
		WHERE
			TITLE ILIKE '%weride%'
	);