SELECT
	*,
	PREVIOUS_RANK - CURRENT_RANK AS RANK_CHANGE
FROM
	(
		SELECT
			KEYWORD,
			COLLECTED_AT,
			RANK AS CURRENT_RANK,
			LAG(RANK) OVER (
				PARTITION BY
					KEYWORD
				ORDER BY
					COLLECTED_AT
			) AS PREVIOUS_RANK
		FROM
			KEYWORD_RANKINGS
	) SUB
WHERE
	COLLECTED_AT = CURRENT_DATE
ORDER BY
	RANK_CHANGE;