SELECT
	A.TITLE,
	A.PUBLISHED_AT,
	A.URL
FROM
	ARTICLES A
	JOIN SOURCES S ON A.SOURCE_ID = S.ID
WHERE
	A.TITLE ILIKE '%Nuclear%'
	OR A.DESCRIPTION ILIKE '%Nuclear%'
ORDER BY
	A.PUBLISHED_AT DESC
LIMIT
	10;